spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  password: 123456
    url: jdbc:mysql://116.62.154.22:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /letseat

wechat:
  mpAppID: wxd2e24***********
  mpAppSecret: b80080d7369fc580059***********
  templateId:
    orderStatus: lbnlSYBmcob9qCm**********************
  
